### PR TITLE
Support Ubuntu and Debian

### PR DESCRIPTION
**Pull request by jokimaki**
Tasks/main.yml had placeholders for Debian and Ubuntu installation. This PR includes setting up an apt repo and installing mongodb-org on Debian and Ubuntu.

Installation steps that are common for RedHat and Debian-based distros have been moved from install.rpm.yml to a separate file. I also added a check to 'configure SELinux for MongoDB' task to see if SELinux is enabled (the task failed otherwise).

The default user and group differ from "mongod" at least on Ubuntu. They must be created before referring to them as a directory owner/group. (This was a bug in RHEL too if someone wanted to change them.)

### CODE REVIEW

**Comment by bcdonadio** [comment]
I tested these changes in our RHEL7.4 lab and I found no regressions. However, I do not have a Debian/Ubuntu lab to also run them right now, so I will be relying in the tests made on your end for those, ok?

**Comment by jokimaki** [comment]
That's OK to me. I tested the changes with Vagrant boxes geerlingguy/ubuntu1604 and debian/jessie64.

Some automated testing would be nice too. Any thoughts on adding for example a Travis setup?

**Comment by bcdonadio** [comment]
Indeed, some automated tests would be nice. However, this isn't the easiest role to write a molecule test or something like that, since the main feature of the role is replica set orchestration, and therefore at least 3 instances would have to be brought up, orchestrated and being able to talk to each other on the CI environment.

I will do that in the future, but I had not the time or need to do it so far.

Anyway, I will be merging your PR. Thank you very much for your contribution!

**Comment by jokimaki** [comment]
Agreed, testing a replica set cluster will require an effort. A single node test could be a beneficial first step, for example to see if a new (or some older) version of MongDB installs at all.

Thank you for taking your time to have a look at this PR and merging it! As you're probably not using Ubuntu yourself I really appreciate it!

**Comment by bcdonadio** [comment]
@jokimaki Just a followup: I've just merged some initial unit testing code, along with Travis integration. :)

https://github.com/stone-payments/ansible-mongodb/pull/3

**Pull request merged**
